#dec
#Load all dec
kalamos.1 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.1.dec.csv", encoding = "UTF-8")
kalamos.2 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.2.dec.csv", encoding = "UTF-8")
kalamos.3 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.3.dec.csv", encoding = "UTF-8")
kalamos.4 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.4.dec.csv", encoding = "UTF-8")
kalamos.5 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.5.dec.csv", encoding = "UTF-8")
kalamos.6 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.6.dec.csv", encoding = "UTF-8")
kalamos.7 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.7.dec.csv", encoding = "UTF-8")
kalamos.8 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.8.dec.csv", encoding = "UTF-8")
kalamos.9 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.9.dec.csv", encoding = "UTF-8")
kalamos.10 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.10.dec.csv", encoding = "UTF-8")
kalamos.11 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.11.dec.csv", encoding = "UTF-8")
kalamos.12 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.12.dec.csv", encoding = "UTF-8")
kalamos.13 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.13.dec.csv", encoding = "UTF-8")
kalamos.14 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.14.dec.csv", encoding = "UTF-8")
kalamos.15 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.15.dec.csv", encoding = "UTF-8")
kalamos.16 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.16.dec.csv", encoding = "UTF-8")
kalamos.17 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.17.dec.csv", encoding = "UTF-8")
kalamos.18 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.18.dec.csv", encoding = "UTF-8")
kalamos.19 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.19.dec.csv", encoding = "UTF-8")
kalamos.20 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.20.dec.csv", encoding = "UTF-8")
kalamos.21 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.21.dec.csv", encoding = "UTF-8")
kalamos.22 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.22.dec.csv", encoding = "UTF-8")
kalamos.23 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.23.dec.csv", encoding = "UTF-8")
kalamos.24 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.24.dec.csv", encoding = "UTF-8")
kalamos.25 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.25.dec.csv", encoding = "UTF-8")
kalamos.26 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.26.dec.csv", encoding = "UTF-8")
kalamos.27 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.27.dec.csv", encoding = "UTF-8")
kalamos.28 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.28.dec.csv", encoding = "UTF-8")
kalamos.29 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.29.dec.csv", encoding = "UTF-8")
rm(kalamos.1.2)
kalamos.dec <- rbind(kalamos.1, kalamos.2, kalamos.3, kalamos.4, kalamos.5, kalamos.6, kalamos.7, kalamos.8, kalamos.9, kalamos.10, kalamos.11, kalamos.12, kalamos.13, kalamos.14, kalamos.15, kalamos.16, kalamos.17, kalamos.18, kalamos.19, kalamos.20, kalamos.21, kalamos.22, kalamos.23, kalamos.24, kalamos.25, kalamos.26, kalamos.27, kalamos.28, kalamos.29)
write.csv(kalamos.dec, file="/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.rep.total.csv")

rm(list = ls())
cat("\014")
