#dec
#Load all dec

finalresults.1 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.1.int.csv", encoding = "UTF-8")
finalresults.2 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.2.int.csv", encoding = "UTF-8")
finalresults.3 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.3.int.csv", encoding = "UTF-8")
finalresults.4 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.4.int.csv", encoding = "UTF-8")
finalresults.5 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.5.int.csv", encoding = "UTF-8")
finalresults.6 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.6.int.csv", encoding = "UTF-8")
finalresults.7 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.7.int.csv", encoding = "UTF-8")
finalresults.8 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.8.int.csv", encoding = "UTF-8")
finalresults.9 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.9.int.csv", encoding = "UTF-8")
finalresults.10 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.10.int.csv", encoding = "UTF-8")
finalresults.11 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.11.int.csv", encoding = "UTF-8")
finalresults.12 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.12.int.csv", encoding = "UTF-8")
finalresults.13 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.13.int.csv", encoding = "UTF-8")
finalresults.14 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.14.int.csv", encoding = "UTF-8")
finalresults.15 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.15.int.csv", encoding = "UTF-8")
finalresults.16 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.16.int.csv", encoding = "UTF-8")
finalresults.17 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.17.int.csv", encoding = "UTF-8")
finalresults.18 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.18.int.csv", encoding = "UTF-8")
finalresults.19 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.19.int.csv", encoding = "UTF-8")
finalresults.20 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.20.int.csv", encoding = "UTF-8")
finalresults.21 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.21.int.csv", encoding = "UTF-8")
finalresults.22 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.22.int.csv", encoding = "UTF-8")
finalresults.23 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.23.int.csv", encoding = "UTF-8")
finalresults.24 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.24.int.csv", encoding = "UTF-8")
finalresults.25 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.25.int.csv", encoding = "UTF-8")
finalresults.26 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.26.int.csv", encoding = "UTF-8")
finalresults.27 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.27.int.csv", encoding = "UTF-8")
finalresults.28 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.28.int.csv", encoding = "UTF-8")
finalresults.29 <- read.csv("/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.29.int.csv", encoding = "UTF-8")

finalresults.int <- rbind(finalresults.1, finalresults.2, finalresults.3, finalresults.4, finalresults.5, finalresults.6, finalresults.7, finalresults.8, finalresults.9, finalresults.10, finalresults.11, finalresults.12, finalresults.13, finalresults.14, finalresults.15, finalresults.16, finalresults.17, finalresults.18, finalresults.19, finalresults.20, finalresults.21, finalresults.22, finalresults.23, finalresults.24, finalresults.25, finalresults.26, finalresults.27, finalresults.28,finalresults.29)

write.csv(finalresults.int, file = "/media/stathis/Maxtor/georeference/kalamos/processed/kalamos.total.int.csv")


rm(list = ls())
cat("\014")
