#dec
#Load all dec

Kalamos_tw.1 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.1.int.csv", encoding = "UTF-8")
Kalamos_tw.2 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.2.int.csv", encoding = "UTF-8")
Kalamos_tw.3 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.3.int.csv", encoding = "UTF-8")
Kalamos_tw.4 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.4.int.csv", encoding = "UTF-8")
Kalamos_tw.5 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.5.int.csv", encoding = "UTF-8")
Kalamos_tw.6 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.6.int.csv", encoding = "UTF-8")
Kalamos_tw.7 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.7.int.csv", encoding = "UTF-8")
Kalamos_tw.8 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.8.int.csv", encoding = "UTF-8")
Kalamos_tw.9 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.9.int.csv", encoding = "UTF-8")
Kalamos_tw.10 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.10.int.csv", encoding = "UTF-8")
Kalamos_tw.11 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.11.int.csv", encoding = "UTF-8")
Kalamos_tw.12 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.12.int.csv", encoding = "UTF-8")
Kalamos_tw.13 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.13.int.csv", encoding = "UTF-8")
Kalamos_tw.14 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.14.int.csv", encoding = "UTF-8")
Kalamos_tw.15 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.15.int.csv", encoding = "UTF-8")
Kalamos_tw.16 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.16.int.csv", encoding = "UTF-8")
Kalamos_tw.17 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.17.int.csv", encoding = "UTF-8")
Kalamos_tw.18 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.18.int.csv", encoding = "UTF-8")
Kalamos_tw.19 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.19.int.csv", encoding = "UTF-8")
Kalamos_tw.20 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.20.int.csv", encoding = "UTF-8")
Kalamos_tw.21 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.21.int.csv", encoding = "UTF-8")
Kalamos_tw.22 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.22.int.csv", encoding = "UTF-8")
Kalamos_tw.23 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.23.int.csv", encoding = "UTF-8")
Kalamos_tw.24 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.25 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.26 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.27 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.28 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.29 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.30 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.31 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.32 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.33 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.34 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.35 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.36 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.37 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.38 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.39 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")
Kalamos_tw.40 <- read.csv("/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.24.int.csv", encoding = "UTF-8")

Kalamos_tw.int <- rbind(Kalamos_tw.1, Kalamos_tw.2, Kalamos_tw.3, Kalamos_tw.4, Kalamos_tw.5, Kalamos_tw.6, Kalamos_tw.7, Kalamos_tw.8, Kalamos_tw.9, Kalamos_tw.10, Kalamos_tw.11, Kalamos_tw.12, Kalamos_tw.13, Kalamos_tw.14, Kalamos_tw.15, Kalamos_tw.16, Kalamos_tw.17, Kalamos_tw.18, Kalamos_tw.19, Kalamos_tw.20, Kalamos_tw.21, Kalamos_tw.22, Kalamos_tw.23, Kalamos_tw.24, Kalamos_tw.25, Kalamos_tw.26, Kalamos_tw.27, Kalamos_tw.28, Kalamos_tw.29, Kalamos_tw.30, Kalamos_tw.31, Kalamos_tw.32, Kalamos_tw.33, Kalamos_tw.34, Kalamos_tw.35, Kalamos_tw.36, Kalamos_tw.37, Kalamos_tw.38, Kalamos_tw.39, Kalamos_tw.40)
write.csv(Kalamos_tw.int, file = "/home/stathis/Desktop/kalamos_r_script/processed/replicated/Kalamos_tw.int.total.csv")
View(Kalamos_tw.int)

rm(list = ls())
cat("\014")